### ISSUE TITLE
Sizing issues on smaller screens

### ISSUE THREAD

**Issue by james090500** [M6yo/NameMCplus#13]
On my laptop, NameMC+ causes the website to get re-arranged.

Without Extension:
![image](https://user-images.githubusercontent.com/20372645/132523364-4fe5f835-3d37-4ea3-8810-11e9384daaf1.png)

With Extension:
![image](https://user-images.githubusercontent.com/20372645/132523449-aeab0d64-534b-489f-a424-9da0f3bdf40f.png)

**Comment by noahmaue** [comment]
Hello! We're sorry this happened! Could you possibly send some more info on your device so we can get to the bottom of this? Thanks!
Example:
Screen Resolution: 1920x1080
Computer Model: MacBook Air (2020)
Browser: Google Chrome
Extra Notes: *insert any other stuff that might help us find the issue*

**Comment by james090500** [comment]
Screen Resolution: 2560 x 1440
Windows Scale: 175%
Browser: Chrome

![image](https://user-images.githubusercontent.com/20372645/132546293-6cee3c79-b626-494d-b6f1-843f75f74748.png)


Looks to do with the set width/height in the canvas.

**Comment by bribes** [comment]
Hmm I cannot seem to reproduce this effect on the latest update can you confirm if this still happens on the latest update? Thanks.

**Comment by noahmaue** [comment]
I'm still able to reproduce this bug, but only on my MacBook
