### ISSUE TITLE
capes show unselected

### ISSUE THREAD

**Issue by MoTai80S5** [M6yo/NameMCplus#17]
if i load on to a profile that has a custom cape from labymod, minecraftcapes.net or cloaks+ the cape isn't selected
![image](https://user-images.githubusercontent.com/77055841/133924465-95392974-04cd-44de-8a6d-38c8f8946d6a.png)

**Comment by noahmaue** [comment]
This is an intentional feature, so you can view a skin without a cape. Simply hovering over the capes will permanently make that cape appear on the skin until the page is refreshed, thus there would be no way to see a capeless version of the user. Thank you for your concerns, though!
