### ISSUE TITLE
Dinnerbone is not rendered upside-down 

### ISSUE THREAD

**Issue by Covkie** [M6yo/NameMCplus#18]
[with NameMCplus](https://cookies.life-is-pa.in/5aV14pRxe)

[without NameMCplus](https://cookies.life-is-pa.in/5aV1z1SCr)

~~also the player render area seems to be smaller with NameMCplus, I don't know if this is intentional or not.~~

**Comment by bribes** [comment]
We will try to fix this issue, thank you for reporting!

**Comment by bribes** [comment]
Fixed in the Upside Down Update.
