### ISSUE TITLE
migrator capes dont equip on profiles with it on even if it is equipped

### ISSUE THREAD

**Issue by 44444444444444444444444444444444444444** [M6yo/NameMCplus#22]
fix this i wanna see my hot rare og migrator cape

**Comment by 44444444444444444444444444444444444444** [comment]
https://youtu.be/jSAFOIeLsbg

**Comment by noahmaue** [comment]
just hover over the cape lmao it's not that hard

**Comment by 44444444444444444444444444444444444444** [comment]
> just hover over the cape lmao it's not that hard

but this is a bug and capes dont show up

**Comment by 44444444444444444444444444444444444444** [comment]
its with all capes also turns out not just migrator capes

**Comment by 44444444444444444444444444444444444444** [comment]
should probably kinda maybe be fixed?????????

**Comment by bribes** [comment]
No, it's suppose to be like this so you can see the skin without any cape on. Then when you want to see the cape you just hover over it. This isn't a bug this is intended.

**Comment by 44444444444444444444444444444444444444** [comment]
thats stupid

**Comment by 44444444444444444444444444444444444444** [comment]
shit piss balls dumb

**Comment by bribes** [comment]
How though, you can still see the cape on the players back.

**Comment by Jiingy** [comment]
What about having a toggle to decide whether you'd like capes on/off by default?
