### ISSUE TITLE
wildcarding using * and ? doesnt work

### ISSUE THREAD

**Issue by tanpug** [M6yo/NameMCplus#4]
![image](https://user-images.githubusercontent.com/60798276/123742935-56864700-d861-11eb-92fe-24822d6d97ba.png)
![image](https://user-images.githubusercontent.com/60798276/123742963-5ede8200-d861-11eb-8c28-a473527f847d.png)

**Comment by emmsixx** [comment]
Thank you for letting me know, will fix asap

**Comment by tanpug** [comment]
love u

**Comment by emmsixx** [comment]
Done, I put in a quick fix which should be fine for the time being. If you encounter any issues please let me know.
